/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as classes from "./classes";
export type { classes };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MasterContract } from "./MasterContract";
export type { MasterRegister } from "./MasterRegister";
