/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as classes from "./classes";
export * as interfaces from "./interfaces";
export { MasterContract__factory } from "./MasterContract__factory";
export { MasterRegister__factory } from "./MasterRegister__factory";
